### ISSUE TITLE
… が全角幅でない

### ISSUE THREAD

**Issue by hokorobi** [rbtnn/vim-ambiwidth#1]
フォントによっては必要ないので、追加の対象を設定で指定できると良さそうかなと思いました。
https://github.com/rbtnn/vim-ambiwidth/compare/main...hokorobi:vim-ambiwidth:dev こんな感じで。

**Comment by rbtnn** [comment]
いいですね。そのまま採用させていただきました。ありがとうございます。

**Comment by hokorobi** [comment]
ありがとうございます！
